name: Pull Request
description: Submit a pull request to contribute to the project
title: "[PR]: "

body:
  - type: dropdown
    id: change_type
    attributes:
      label: Type of Change
      description: What kind of change does this PR introduce?
      options:
        - Bug fix
        - New feature
        - Documentation update
        - Other (please describe in description)
      default: 0
    validations:
      required: true

  - type: input
    id: issue_fixes
    attributes:
      label: Fixes Issue
      description: Please provide the issue number this PR fixes (if applicable)
      placeholder: "Fixes #123"
    validations:
      required: false

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Please provide a summary of the changes
      placeholder: Describe your changes here
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Before submitting your PR, please make sure to check the following.
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/AgilianX/.github/blob/main/CONTRIBUTING.md)
          required: true
        - label: I have tested my changes
          required: true
        - label: I have updated documentation as needed
          required: true
