name: Bug Report
description: Report a reproducible bug or regression
title: "[Bug]: "
labels: [bug]

body:
  - type: markdown
    attributes:
      value: Thanks for reporting a bug! Please fill out the form below to help us reproduce and fix it.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, version, etc.
      placeholder: e.g. Windows 11, v0.1.0, etc
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Describe the steps to reproduce the issue.
      placeholder: |
        1. Run application
        2. Fry CPU
        3. Buy new computer
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: eg. Honestly? Nothing special
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: eg. I dropped my croissant...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Screenshots
      description: Paste any relevant logs or screenshots.
    validations:
      required: false
