name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature Request]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: Thank you for your suggestion! Please provide details below.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see.
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this feature important?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternatives?
    validations:
      required: false
